---
name: dummy

releases:
- name: bosh-govmomi-cpi
  url: ((cpi_url))

jobs:
- name: dummy
  instances: 1
  templates:
  - {name: govmomi_cpi, release: bosh-govmomi-cpi}
  resource_pool: default
  networks:
  - {name: default, static_ips: [((vm_ip))]}

resource_pools:
- name: default
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    url: ((stemcell_url))
  network: default
  cloud_properties: {}

networks:
- name: default
  subnets:
  - dns:
    - 10.0.0.2
    gateway: 10.0.0.1
    range: 10.0.0.0/24
    static_ips: ((vm_ip))
    cloud_properties:
      net_id: ((net_id))
      security_groups: ((default_security_groups))
  type: manual

compilation:
  workers: 5
  network: default
  cloud_properties: {}

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000 - 90000
  update_watch_time: 5000 - 15000

cloud_provider:
  mbus: https://mbus:p2an3m7idfm6vmqp3w74@((vm_ip)):6868
  template:
    name: govmomi_cpi
    release: bosh-govmomi-cpi
  ssh_tunnel:
    host: ((vm_ip)) # <--- Replace with your Elastic IP address
    port: 22
    user: vcap
    private_key: ./state/bosh.pem # Path relative to this manifest file
  properties:
    agent:
      mbus: https://mbus:p2an3m7idfm6vmqp3w74@0.0.0.0:6868
    blobstore:
      path: /var/vcap/micro_bosh/data/cache
      provider: local
    vcenter: &vcenter # <--- Replace values below
      address: ((vcenter_address))
      user: ((vcenter_user))
      password: ((vcenter_password))
      datacenters:
      - name: ((vcenter_datacenter))
        vm_folder: BOSH_VMs
        template_folder: BOSH_Templates
        datastore_pattern: ((vcenter_datastore))
        disk_path: bosh_disks
        clusters: []
    ntp:
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com

resource_pools:
- name: default
  network: default
  stemcell:
    url: ((stemcell_url))
  cloud_properties:
    instance_type: concourse
  env:
    bosh:
      password: '*'
